# Generated by Django 3.0.3 on 2020-03-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200315_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
